

cmake \
    -DOPENCV_FP16_DISABLE:BOOL=1 \
    -DBUILD_FAT_JAVA_LIB:BOOL=0 \
    -DBUILD_SHARED_LIBS:BOOL=0 \
    -DBUILD_OPENCV_WORLD:BOOL=1 \
    -DBUILD_TESTS:BOOL=0 \
    -DBUILD_EXAMPLES:BOOL=0 \
    -DBUILD_ANDROID_EXAMPLES:BOOL=0 \
    -DBUILD_PERF_TESTS:BOOL=0 \
    -DWITH_TBB:BOOL=1